In [1]:
import numpy as np


arr = np.array([1, 5, 50, 7, 9])

print(arr)

print(type(arr))



[ 1  5 50  7  9]
<class 'numpy.ndarray'>


In [2]:
import numpy as np

arr = np.array(("Santosh", "Hariom", "Radhe Shyam"))
print(arr)

['Santosh' 'Hariom' 'Radhe Shyam']


In [3]:
import numpy as np

# 0-D Arrays
arr = np.array(42)
print(arr)

42


In [4]:
import numpy as np

# 1-D Arrays
arr = np.array([42, 4, 6, 7, 8, 9])
print(arr)

[42  4  6  7  8  9]


In [10]:
import numpy as np

# 2-D Arrays
arr = np.array([[42, 4, 6], ["Ram", "Hanuman", "Laxman"]])
print(arr)

[['42' '4' '6']
 ['Ram' 'Hanuman' 'Laxman']]


In [14]:
import numpy as np

# 3-D Arrays
arr = np.array([[42, 4, 6], ["Ram", "Hanuman", "Laxman"], [420, 400, 600]])
print(arr)

[['42' '4' '6']
 ['Ram' 'Hanuman' 'Laxman']
 ['420' '400' '600']]


In [16]:
import numpy as np

# check number of dimension
arr1 = np.array([[[42, 4, 6], ["Ram", "Hanuman", "Laxman"], [420, 400, 600]]])
arr2 = np.array([[42, 4, 6], ["Ram", "Hanuman", "Laxman"]])
arr3 = np.array([42, 4, 6, 7, 8, 9])
arr4 = np.array(42)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)


3
2
1
0


In [19]:
import numpy as np


# Higher Dimensional Arrays using - "ndmin"
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print(type(arr))
print("Number of dim: ", arr.ndim)

[[[[[1 2 3 4]]]]]
<class 'numpy.ndarray'>
Number of dim:  5
